### ISSUE TITLE
AttributeError: 'module' object has no attribute 'th_Double_fft2'

### ISSUE THREAD

**Issue by kingkongkai** [locuslab/pytorch_fft#5] opened 2017-07-02 16:54 UTC
I get the following error:

File "/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/pytorch_fft/fft/fft.py", line 41, in fft2
f = th_fft.th_Double_fft2
AttributeError: 'module' object has no attribute 'th_Double_fft2'

Any idea how to fix this?

**Comment by riceric22** [comment] 2017-07-02 17:44
What version of python, pytorch, and pytorch_fft are you using? I just tried a fresh install of 2.7.13 with the latest version of pytorch_fft and couldn't reproduce (pytorch 0.1.12) the issue.

**Comment by kingkongkai** [comment] 2017-07-04 10:54
$ pip freeze | grep torch
pytorch-fft==0.10
torch==0.1.12.post2

$ pip freeze | grep ffi
cffi==1.10.0

$ python --version
Python 2.7.13 :: Anaconda custom (64-bit)

I'm using all the same versions on a separate computer, on which pytorch_fft seems to work with no problems. I've tried pip uninstalling and installing again. Any other ideas for what I can try to do?

**Comment by riceric22** [comment] 2017-07-04 15:59
Can you clone the repo on the non working system, run `python build.py`, and post the output?

**Comment by kingkongkai** [comment] 2017-07-05 09:18
I don't have super user privileges, but I hope 'python setup.py install' will be ok too:

$ python setup.py install
Including CUDA code.
Including CUDA code.
running install
running bdist_egg
running egg_info
creating pytorch_fft.egg-info
writing requirements to pytorch_fft.egg-info/requires.txt
writing pytorch_fft.egg-info/PKG-INFO
writing top-level names to pytorch_fft.egg-info/top_level.txt
writing dependency_links to pytorch_fft.egg-info/dependency_links.txt
writing manifest file 'pytorch_fft.egg-info/SOURCES.txt'
reading manifest file 'pytorch_fft.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pytorch_fft.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pytorch_fft
copying pytorch_fft/__init__.py -> build/lib.linux-x86_64-2.7/pytorch_fft
creating build/lib.linux-x86_64-2.7/pytorch_fft/_ext
copying pytorch_fft/_ext/__init__.py -> build/lib.linux-x86_64-2.7/pytorch_fft/_ext
creating build/lib.linux-x86_64-2.7/pytorch_fft/fft
copying pytorch_fft/fft/__init__.py -> build/lib.linux-x86_64-2.7/pytorch_fft/fft
copying pytorch_fft/fft/fft.py -> build/lib.linux-x86_64-2.7/pytorch_fft/fft
copying pytorch_fft/fft/autograd.py -> build/lib.linux-x86_64-2.7/pytorch_fft/fft
creating build/lib.linux-x86_64-2.7/pytorch_fft/_ext/th_fft
copying pytorch_fft/_ext/th_fft/__init__.py -> build/lib.linux-x86_64-2.7/pytorch_fft/_ext/th_fft
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/pytorch_fft._ext.th_fft._th_fft.c'
creating build/temp.linux-x86_64-2.7
building 'pytorch_fft._ext.th_fft._th_fft' extension
creating build/temp.linux-x86_64-2.7/build
creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/home
creating build/temp.linux-x86_64-2.7/home/stoffers
creating build/temp.linux-x86_64-2.7/home/stoffers/pytorch_fft
creating build/temp.linux-x86_64-2.7/home/stoffers/pytorch_fft/pytorch_fft
creating build/temp.linux-x86_64-2.7/home/stoffers/pytorch_fft/pytorch_fft/src
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/stoffers/pytorch_fft/pytorch_fft/src -I/packages/development/anaconda/2-4.3.1/include/python2.7 -c build/temp.linux-x86_64-2.7/pytorch_fft._ext.th_fft._th_fft.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/pytorch_fft._ext.th_fft._th_fft.o
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/stoffers/pytorch_fft/pytorch_fft/src -I/packages/development/anaconda/2-4.3.1/include/python2.7 -c /home/stoffers/pytorch_fft/pytorch_fft/src/th_fft_cuda.c -o build/temp.linux-x86_64-2.7/home/stoffers/pytorch_fft/pytorch_fft/src/th_fft_cuda.o
gcc -pthread -shared -L/packages/development/anaconda/2-4.3.1/lib -Wl,-rpath=/packages/development/anaconda/2-4.3.1/lib,--no-as-needed build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/pytorch_fft._ext.th_fft._th_fft.o build/temp.linux-x86_64-2.7/home/stoffers/pytorch_fft/pytorch_fft/src/th_fft_cuda.o -L/usr/local/cuda/lib64 -L/packages/development/anaconda/2-4.3.1/lib -lcufft -lpython2.7 -o build/lib.linux-x86_64-2.7/pytorch_fft/_ext/th_fft/_th_fft.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pytorch_fft
copying build/lib.linux-x86_64-2.7/pytorch_fft/__init__.py -> build/bdist.linux-x86_64/egg/pytorch_fft
creating build/bdist.linux-x86_64/egg/pytorch_fft/fft
copying build/lib.linux-x86_64-2.7/pytorch_fft/fft/autograd.py -> build/bdist.linux-x86_64/egg/pytorch_fft/fft
copying build/lib.linux-x86_64-2.7/pytorch_fft/fft/__init__.py -> build/bdist.linux-x86_64/egg/pytorch_fft/fft
copying build/lib.linux-x86_64-2.7/pytorch_fft/fft/fft.py -> build/bdist.linux-x86_64/egg/pytorch_fft/fft
creating build/bdist.linux-x86_64/egg/pytorch_fft/_ext
creating build/bdist.linux-x86_64/egg/pytorch_fft/_ext/th_fft
copying build/lib.linux-x86_64-2.7/pytorch_fft/_ext/th_fft/_th_fft.so -> build/bdist.linux-x86_64/egg/pytorch_fft/_ext/th_fft
copying build/lib.linux-x86_64-2.7/pytorch_fft/_ext/th_fft/__init__.py -> build/bdist.linux-x86_64/egg/pytorch_fft/_ext/th_fft
copying build/lib.linux-x86_64-2.7/pytorch_fft/_ext/__init__.py -> build/bdist.linux-x86_64/egg/pytorch_fft/_ext
byte-compiling build/bdist.linux-x86_64/egg/pytorch_fft/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytorch_fft/fft/autograd.py to autograd.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytorch_fft/fft/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytorch_fft/fft/fft.py to fft.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytorch_fft/_ext/th_fft/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pytorch_fft/_ext/__init__.py to __init__.pyc
creating stub loader for pytorch_fft/_ext/th_fft/_th_fft.so
byte-compiling build/bdist.linux-x86_64/egg/pytorch_fft/_ext/th_fft/_th_fft.py to _th_fft.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pytorch_fft.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytorch_fft.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytorch_fft.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytorch_fft.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pytorch_fft.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pytorch_fft-0.10-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pytorch_fft-0.10-py2.7-linux-x86_64.egg
Copying pytorch_fft-0.10-py2.7-linux-x86_64.egg to /packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages
Adding pytorch-fft 0.10 to easy-install.pth file
Installed /packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/pytorch_fft-0.10-py2.7-linux-x86_64.egg
Processing dependencies for pytorch-fft==0.10
Searching for cffi==1.10.0
Best match: cffi 1.10.0
Adding cffi 1.10.0 to easy-install.pth file
Using /packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages
Searching for pycparser==2.17
Best match: pycparser 2.17
Adding pycparser 2.17 to easy-install.pth file
Using /packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages
Finished processing dependencies for pytorch-fft==0.10

**Comment by kingkongkai** [comment] 2017-07-06 09:52
It works for python 3, so I'm switching to that. Problem solved! :+1: Sort of. :-)

**Comment by kojimano** [comment] 2017-10-12 02:00
A similar issue happened to me.

Error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kojimano/.conda/envs/condaroot/lib/python2.7/site-packages/pytorch_fft/fft/fft.py
    f = th_fft.th_Float_fft2
AttributeError: 'module' object has no attribute 'th_Float_fft2'

After:
>>> import pytorch_fft.fft as fft
>>> import torch
>>> A_real, A_imag = torch.randn(3,4,5).cuda(), torch.zeros(3,4,5).cuda()
>>> B_real, B_imag = fft.fft2(A_real, A_imag)

Package Version:
pytorch-fft==0.13
torch==0.2.0.post4
torchvision==0.1.9
Python 2.7.13 :: Anaconda custom (64-bit)

**Comment by kojimano** [comment] 2017-10-12 02:34
Output from python build.py
![2017-10-11 22 33 23](https://user-images.githubusercontent.com/18011504/31476429-49022a78-aed4-11e7-8403-dab650ab32bb.png)

**Comment by riceric22** [comment] 2017-10-13 18:34
From the image, the C extension failed to build because it couldn't link to cuda.h. Can you make sure cuda is linked in your path?

**Comment by kojimano** [comment] 2017-10-18 15:01
Sorry that was my mistake. Now after setting up Cuda module correctly, I am getting this message.
![2017-10-18 11 00 37](https://user-images.githubusercontent.com/18011504/31725987-b34a2240-b3f3-11e7-9b9d-db9cec0f2d01.png)

**Comment by kojimano** [comment] 2017-10-22 21:25
Couldn't figure out the issue, but works fine after replacing /pytorch_fft/_ext/th_fft/_th_fft.so with same files of someone else who are not suffering from this issue.

**Comment by riceric22** [comment] 2017-10-23 18:54
It looks like the pytorch extension is still not being built, so it would make sense that if someone gave you the already-built shared library files then it would work. If anyone else is having this issue, I would recommend that you try to build the sample ffi extensions [here](https://github.com/pytorch/extension-ffi) first to make sure the pipeline works.

**Comment by riceric22** [comment] 2018-02-19 23:53
The error found by @kojimano is actually a separate issue and was closed in #23

**Closed by riceric22** 2018-02-19 23:53 UTC
